---
title: "NMsim Examples"
output:
rmarkdown::html_document:
    toc: true
    code_folding: show
Suggests: markdown
VignetteBuilder: knitr
vignette: >
  %\VignetteIndexEntry{Typical}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
header-includes:
- \usepackage{ae}
---


```{css echo=FALSE}


h1.title { /* title style */
  margin-top:2em;
  margin-bottom:1em;
  font-size:40px;
}

body{ /* body style */
      font-size: 18px;
}

.subheading h1 {  /* subheading style */
  font-weight:bold;
  font-size:40px;
}

.authors h4 {  /* author style */
  font-weight:bold;
  font-style:italic;
  margin-top: 0em;
  margin-bottom: 0.5em;
}

.date h4 {  /* date style */
  font-weight:bold;
  margin-top: 0em;
  margin-bottom: 5em;
}

.date h4 {  /* plotting chunks style */
  font-weight:bold;
  margin-top: 0em;
  margin-bottom: 5em;
}


.myplot{
  aspect-ratio = 0.5;
  width: 50%;
}

/* -----------div tips------------- */

div.example {  /* layout for examples */
    padding: 1em;
    margin-bottom: 2em;
    padding-left: 50px;
    background-size: 30px;
    background-repeat: no-repeat;
    background-position: 10px 10px;
    min-height: 40px;
    font-size: 16px;
    color: #000000;
    border: solid 5px #dfedff;
}

  
``` 

```{r setup, include=FALSE}
#--- Set up options ---# 

knitr::opts_knit$set(verbose=T)
knitr::opts_chunk$set(echo = F, warning = F)
```


:::example

# NMsim - Seamless NONMEM Simulation Platform in R {.subheading .tabset}

#### Authors: Philip Delff {.authors}
#### Last updated: `r format(Sys.time(), '%B %d, %Y')` {.date}

## Part 1 

* Here be examples 

```{r iris} {.myplot}

x= "Here we have some code"

library(ggplot2, warn.conflicts = F, quietly = T)
ggplot(data=iris, aes(x = Sepal.Length, y = Sepal.Width))+
  geom_point()

```


## Part 2

just some more text
`r 2+5`

:::





:::example

# NMsim - Simulation-Based Forest Plots with NMsim {.subheading .tabset}

#### Authors: Philip Delff, Boris Grinshpun {.authors}
#### Last updated: `r format(Sys.time(), '%B %d, %Y')` {.date}

* Here be examples 

```{r}

x= "Here we have some code 2"


```


:::
        
        
